name: flutter_ume
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 0.2.0-dev.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.6
  vm_service: ^7.1.1
  string_scanner: ^1.1.0
  tuple: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: git@github.com:amondnet/flutter_coverage_badge.git
      ref: master

flutter:
