name: flutter_ume_kit_perf
description: Performance kits for flutter_ume.
version: 0.1.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  flutter_coverage_badge: ^0.0.1+1

flutter:
