name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 0.2.0-dev.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  flutter_ume: '>=0.2.0-dev.0 <0.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/amondnet/flutter_coverage_badge.git
      ref: master

flutter:
